apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxx
  namespace: nginxx
  labels:
    app: nginxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxx
  template:
    metadata:
      labels:
        app: nginxx
    spec:
      containers:
        - name: nginxx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
