apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxx
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: nginxx.afpadevops.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxx-nodeport
            port:
              number: 80
