apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxx
  namespace: nginxx
spec:
  ingressClassName: traefik
  rules:
    - host: nginxx.afpadevops.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginxx-clusterip
                port:
                  number: 80
